### ISSUE TITLE
Expand Abbreviation conflicts with the default emacs "end-of-line" shortcut

### ISSUE THREAD

**Issue by jlom** [emmetio/nova-plugin#10]
**Describe the bug**
Currently, <kbd>⌃</kbd>+<kbd>E</kbd> is set as the default shortcut for Expand Abbreviation. However, this conflicts with the default emacs "end of line"-shortcut, and as far as I can tell, there's no way to get the default mapping back?

**To Reproduce**
1. Have the Emmet plugin installed.
2. Place the cursor at the middle of a line of code.
3. Press <kbd>⌃</kbd>+<kbd>E</kbd>

**Expected behavior**
The cursor is moved to the end of the current line.

**Actual behavior**
The Emmet plugin tries to expand whatever piece of text it's at.

**Environment (please complete the following information):**
 - Nova version: 1.0.0b15
 - Emmet extension version: 1.2.2

**Additional context**
Even if I try remapping Expand Abbreviation manually to something else (though App Shortcuts in System Preferences), the default "end-of-line" behaviour isn't restored: Then the alert sound is played, and the cursor stays put.

**Comment by sergeche** [comment]
You can change key bindings via Preferences > Key Bindings
<img width="832" alt="image" src="https://user-images.githubusercontent.com/93595/85384634-01c33880-b54a-11ea-905d-2011f363979e.png">

**Comment by jlom** [comment]
Ah, perfect, thanks! 🎉
