### ISSUE TITLE
Support for Blade Templates

### ISSUE THREAD

**Issue by elliottregan** [emmetio/nova-plugin#15]
**Describe the solution you'd like**
I'd like to see Emmet expansion expanded to work in Laravel Blade templates (*.blade.php).

**Additional context**
The VS Code extension's way of handling this to tell the extension which file types to treat as HTML. I'm not sure what's going on under the hood, but it seems to be a generic solution that allows Emmet to work in any file type, whether it is .erb, .blade.php, .asdf, etc.

**Comment by sergeche** [comment]
Added in v1.2.3
