### ISSUE TITLE
Disable file types setting / No CSS auto-complete

### ISSUE THREAD

**Issue by medienbaecker** [emmetio/nova-plugin#16]
**Describe the solution you'd like**
I would like to disable auto-complete for certain files. I really like Emmet for HTML but I don't use it for CSS.
For now I changed [this line](https://github.com/emmetio/nova-plugin/blob/a2148a73762910dfd3fad95a37049584282fb218/src/lib/syntax.ts#L9) manually as a workaround.

**Additional context**
While you can uncheck the "Enable auto-complete" checkbox globally, it's a lot more convenient to use tab/enter for the completions.

**Comment by sergeche** [comment]
In v1.3.0, there’s "Ignored syntaxes" option where you can enumerate syntaxes where abbreviation completion should be disabled. You can either enumerate specific syntaxes like `css, scss` or use `stylesheet` keyword to completely disable completions for all stylesheet syntaxes
