### ISSUE TITLE
Please add support for Twig-HTML files

### ISSUE THREAD

**Issue by kemmerly** [emmetio/nova-plugin#17]
Would be great to get HTML tab completions working within Twig-HTML files

**Comment by edwardpmartinez** [comment]
+1

**Comment by kylecotter** [comment]
Would love this too!

**Comment by tpmatthes** [comment]
Hey, I’m the author of the Twig plugin for Nova: https://github.com/tpmatthes/Twig.novaextension

It’s true, Emmet doesn’t work in Twig files, if you use the Twig plugin. You can only see completions from the Twig plugin. The Emmet plugin _does_ work in PHP files, though. The built-in PHP syntax definition and the Twig plugin use the same structure. I’ve temporarily removed all completions from the Twig plugin, but it still doesn’t work.

I’ve briefly looked at the code for this plugin. It seems like `"twig"` should be part of `htmlSyntaxes` or `markupSyntaxes` (your allowlist):

https://github.com/emmetio/nova-plugin/blob/a2148a73762910dfd3fad95a37049584282fb218/src/lib/syntax.ts#L8

https://github.com/emmetio/nova-plugin/blob/a2148a73762910dfd3fad95a37049584282fb218/src/lib/syntax.ts#L11

As it seems, the Emmet plugin also doesn’t show completions, if other completions are available. I can definitely tweak the triggers for Twig completions to make that work, but we probably need to add Twig to the allowlist first.

I’ll be happy to provide more infos to help solve this issue. Thanks! 😊

**Comment by freinbichler** [comment]
It would probably best if the allowed file extensions could be customised in the plugin's settings, like it is the case in Atom and VS Code as far as I remember.
However, as a quick fix I would definitely love it if you could add the twig extension to the hardcoded list. 😊

**Comment by sergeche** [comment]
Yes, the best candidate here is `htmlSyntaxes` since Twig is mostly used as HTML subset so Emmet can use features like context capturing and work with tags.

Unfortunately, I can’t do any extension updates right now since my Nova beta license has expired (I don’t use it for development) and Nova devs doesn’t respond to my e-mails about providing me with licence for extension update.
