### ISSUE TITLE
Emmet decrement by 10

### ISSUE THREAD

**Issue by padprint** [emmetio/nova-plugin#22]
**Describe the bug**
Using the shortcut of control + shift + down arrow  increments at number by 10, rather than decrementing 

**To Reproduce**
create a new file and enter a number on a line
use the key combination of control, shift and down arrow to decrement the number by 10

**Expected behavior**
well, to decrement by 10 :)

**Environment (please complete the following information):**
 - Nova version: 2.1 Build 215812
 - Emmet extension version 1.2.3

**Comment by sergeche** [comment]
You can change action shortcuts via Nova settings

**Comment by padprint** [comment]
Changing the shortcut has no effect, the number still increments rather than decrements.
