### ISSUE TITLE
Evaluate Math Expression fails and displays error

### ISSUE THREAD

**Issue by rdaskew** [emmetio/nova-plugin#23]
**Describe the bug**
Evaluate Math Expression fails and displays error

**To Reproduce**
1. Go to any document
2. Type in a math expression such as 25*2 or 30/3 and highlight to select
3. Right click the selection and choose Emmet>Evaluate Math Expression
4. See error in Extension Console - "Error: Parity at column 0 of expression"

**Expected behavior**
Expect: Math Expression is evaluated successfully - (25*2 = 50 or 30/3 = 10)

**Environment (please complete the following information):**
 - Nova version: Nova 3 Build 218855
 - Emmet extension version 1.2.3

**Comment by sergeche** [comment]
There’s no need to select expression, you should put caret right after expression and evaluate it

**Comment by rdaskew** [comment]
Discovered the issue when using the select + right click to trigger from the Emmet option in the right click menu.

Same error and result just using the key combination (⇧⌘Y), which does work successfully in the demo here as an example https://docs.emmet.io/actions/evaluate-math/
