### ISSUE TITLE
Cursor Placement does not work in Version 1.3

### ISSUE THREAD

**Issue by JonasAtZwetschke** [emmetio/nova-plugin#25]
**Describe the bug**
After Updating to 1.3 expanding abbreviations with cursors (${0},${1}) will expand with "${1:0}" as text. Cursor is placed at the end of line.

**To Reproduce**
1. Install the latest Update
2. Expand bgp for example

**Screenshots**
![Bildschirmfoto 2020-12-14 um 11 31 38](https://user-images.githubusercontent.com/11939443/102070915-1220e580-3e00-11eb-8980-433251974f61.png)

**Environment:**
- MacOS 10.15.7
 - Nova version: 3.1
 - Emmet extension version 1.3

I tried reinstalling the extension and restart Nova.

**Comment by sergeche** [comment]
Current Emmet version is 1.3.0, please check for updates

**Comment by JonasAtZwetschke** [comment]
@sergeche Im sorry, i wrote down the last version from the changelog, my installed version is 1.3.
![Bildschirmfoto 2020-12-14 um 12 06 35](https://user-images.githubusercontent.com/11939443/102074374-fe2bb280-3e04-11eb-9820-87b45098a02f.png)

**Comment by sergeche** [comment]
Hmm, can’t confirm this bug, works fine for me

<img width="300" alt="image" src="https://user-images.githubusercontent.com/93595/102075292-17d5f580-3e17-11eb-9f26-bbeff6345ad8.png">

In v1.3.0 I’m using new snippets format, introduced in Nova 1.2, maybe you have outdated Nova?

**Comment by JonasAtZwetschke** [comment]
![Bildschirmfoto 2020-12-14 um 13 06 42](https://user-images.githubusercontent.com/11939443/102079565-3c2cd480-3e0d-11eb-95dc-13155f54a4fd.png)
Think i got the latest version, tried full restart, disable all other extensions, reinstall but the problem remains. 

Last time i worked (on friday) it worked fine, i use this extension every single day, it the most usefull one for me. 
Is it possible to release a older version in GitHub release tab?

**Comment by idiotcomputer** [comment]
I can confirm this bug.

- Mac OS 10.15.7
- Nova 3.1
- Emmet 1.3.0
<img width="142" alt="スクリーンショット 2020-12-15 13 48 36" src="https://user-images.githubusercontent.com/11037759/102172532-4c5fb500-3edc-11eb-85f8-4e2b39dabde6.png">

**Comment by JonasAtZwetschke** [comment]
I am also still on MacOS 10.15.7, added to the description.

**Comment by sergeche** [comment]
Should be fixed in v.1.3.1

**Comment by JonasAtZwetschke** [comment]
Fixed it for me, thank you very much!

**Comment by satolog** [comment]
Arigato!
