### ISSUE TITLE
Not appearing in extension manager

### ISSUE THREAD

**Issue by dragoonDorise** [emmetio/nova-plugin#3]
Hi, I can't find emmet in Nova's extension manager, did you guys pulled it from there? Any other way to manually install it? Thanks!

**Comment by sergeche** [comment]
For some reasons, I can’t deploy it into Extensions Library.
You can download extension from build artifacts, like this: https://github.com/emmetio/nova-plugin/actions/runs/96429557

**Comment by dragoonDorise** [comment]
Thank you, now I can use emmet!!!!

You should put it in the readme so everybody knows you can use emmet with Nova

**Comment by sergeche** [comment]
Extension is now available in Extensions library, please install it to keep version up-to-date
