### ISSUE TITLE
Expanded expressions inserted with incorrect placeholder format

### ISSUE THREAD

**Issue by logancollins** [emmetio/nova-plugin#33]
**Describe the bug**

We released Nova 5 yesterday, and a couple of users have emailed our support with a report that Emmet is no longer inserting placeholders properly when using the "Expand Abbreviation" command. After some investigation, this appears to be due to how Emmet is using the Nova API and a change we made in Nova 5.

For this command, Emmet is using the `editor.edit()` and `edit.insert()` APIs. However, it is providing a format parameter to `edit.insert()` with a value of `InsertTextFormat.Snippet`. This parameter was not supported on this method until Nova 5. The string that Emmet is providing still contains the (non-snippet) placeholder `$[]`. Before Nova 5, JavaScript would ignore this third parameter, but after Nova 5 shipped it's using it, and that is causing the string to be interpreted as a Snippet placeholder string, that should instead take a form like `$0`.

I believe the central point where this is happening [is here](https://github.com/emmetio/nova-plugin/blob/5f9b38b4f2f05045e65dd685123283b9223f458b/src/lib/utils.ts#L52).

**To Reproduce**
1. Enable Emmet within Nova 5
2. Open an HTML file
3. Type an abbreviation, such as `h3.test`
4. Invoke the command for "Expand Abbreviation" (by default, bound to <kbd>Ctrl</kbd><kbd>e</kbd>

**Expected behavior**

The tag is inserted with an editor placeholder in between.

**Screenshots**

![2021-02-23 12 07 11](https://user-images.githubusercontent.com/714246/108901580-e3797500-75cf-11eb-807b-95c6144091f4.gif)

**Environment (please complete the following information):**
 - Nova version: 5
 - Emmet extension version: 1.3.1

**Additional context**

This does not affect completions, on which the Snippet format was supported since Nova 2.

**Comment by sergeche** [comment]
Thank you for detailed report! Fixed this issue in v1.3.2
