### ISSUE TITLE
How to assign Tab key as shortcut?

### ISSUE THREAD

**Issue by megavolkan** [emmetio/nova-plugin#35]
As far as i can tell we cannot assign "Tab" key as shortcut. When tried to do it in Nova/Preferences/Key Bindings instead of registering the key pressed cursor jumps to Search field.

**Comment by sergeche** [comment]
I think this issue should be addressed to Nova devs. I don’t think its possible to assign Tab key, that’s why Emmet works as completion provider so you can complete it with Tab when selected
