### ISSUE TITLE
Completions no longer being offered in JSX files when using Nova 10+

### ISSUE THREAD

**Issue by djambell** [emmetio/nova-plugin#55]
Hello there! Since the release of Nova 10, JSX files now use the standard "JavaScript" syntax, which unfortunately means that completions are no longer being offered in JSX files  as expected.

If you could continue to include the previously supported syntaxes to ensure backward compatibility with older versions, it would be greatly appreciated.

 - Nova version: 10+
 - Emmet extension version: 1.3.3

**Comment by sergeche** [comment]
Hi Aaron,
I guess I need to add `javascript` here?

https://github.com/emmetio/nova-plugin/blob/master/src/lib/syntax.ts#L10

**Comment by djambell** [comment]
Hi Sergey,
Yes, I think that sounds perfect. Thanks so much for the quick reply!

**Comment by sergeche** [comment]
Show work in v1.3.4
