### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by jdsimcoe** [emmetio/nova-plugin#9]
**Describe the solution you'd like**
I would love to see `Tab` completion instead of being forced to use `Ctrl + e`. 

**Additional context**
I've used editors in the past that supported Tab completion and it makes authoring much more seamless.

**Comment by sergeche** [comment]
Emmet already supports Tab expand: https://github.com/emmetio/nova-plugin#expanding-abbreviation
Make sure you’re using supported syntax

**Comment by jdsimcoe** [comment]
Thanks, @sergeche! I must have been in the wrong syntax mode or something. Works beautifully!
